### ISSUE TITLE
Could you provide me with a suitable download link for the AI-TOD-V2 dataset?

### ISSUE THREAD

**Issue by F15319732814fyj** [hoiliu-0801/DQ-DETR#5]
Could you provide me with a suitable download link for the AI-TOD-V2 dataset? The one I downloaded seems to be mismatched.

**Comment by hoiliu-0801** [comment]
I will reach out to the original authors of the AI-TOD dataset for confirmation. If permission is granted, I will upload the dataset to this repository.

**Comment by hoiliu-0801** [comment]
I update the readme. Please check it out for the download link.
